ConfigRuleName: required-tags-check
Description: Ensure resources are tagged with Environment, Owner, and CostCenter
Scope:
  ComplianceResourceTypes:
    - "AWS::EC2::Instance"
    - "AWS::S3::Bucket"
    - "AWS::Lambda::Function"
Source:
  Owner: AWS
  SourceIdentifier: REQUIRED_TAGS
InputParameters:
  tag1Key: "Environment"
  tag2Key: "Owner"
  tag3Key: "CostCenter"
